- include/remollGenericDetector.hh
This was commited as develop 2224d9bb26452f45c0875cb376f564b384e054e3
but it is a bug in current v2.0.1 release (and crashes sometimes).
I closed #92 prematurely after only fixing develop but didn't fix master.
> Merge bugfix for detector sort needs mutex into develop

- include/remollGenericDetector.hh
This was commited as develop 2224d9bb26452f45c0875cb376f564b384e054e3
but it is a bug in current v2.0.1 release (and crashes sometimes).
I closed #92 prematurely after only fixing develop but didn't fix master.
> Merge bugfix for detector sort needs mutex into master and release v2.0.2

- macros/checkoverlap.mac
- macros/pionwall/moller_lead_wall_100mm.in
- macros/pionwall/pion_lead_wall_100mm.in
- macros/printgeometry.mac
- macros/sim_dump_backscatter.mac
- macros/sim_moller.mac
- macros/sim_pion.mac
- macros/tests/commit/test_beam.mac
- macros/tests/commit/test_elastic.mac
- macros/tests/commit/test_elasticAl.mac
- macros/tests/commit/test_elasticAl_DS.mac
- macros/tests/commit/test_elasticAl_US.mac
- macros/tests/commit/test_inelastic.mac
- macros/tests/commit/test_inelasticAl.mac
- macros/tests/commit/test_moller.mac
- macros/tests/commit/test_pion.mac
- macros/tests/commit/test_raster.mac
- macros/tests/release/test_moller.mac
- macros/tests/unit/test_overlap.mac
- macros/tests/valgrind/test_moller.mac
The 'proper' geometry is now in the `geometry` folder. There are
differences in the distributions at the scattering plane.
Will become next bugfix release.
> Avoid using geometry_sculpt in test macros and other examples.

- src/remollGenExternal.cc
Bugfix, will cause fewer travis errors (I realize now).
> Use correct units in remollGenExternal

- src/remollGenericDetector.cc
This fixes #127.
Issues created? Maybe some.
- How do we want to store optical photon hits? Ideally none at all since
the only physical way to detect them is by absorption on a surface...
- This may impact how optical photons (but only optical photons) are
store currently.
> Merge bugfix issue 127: For optical photon that reach geom boundary, store post step point

- rad_analysis/rad_dose.cc
- rad_analysis/rad_dose_Oct20-2018.cc
The cameron_dose_branch tracks the things I worked on for the MOLLER radiation studies. This includes a lot of unnecessary modifications to stepping action and other related files whose functionality was abandoned but not deleted.
However, the updates I made to my rad_analysis scripts are all tracked in here (and should be cherry-picked into the sbujlab/rad_analysis repository so they are tracked there correctly instead of just copied files as they are now)
Additionally, the updates I made to the geometry files are mostly tracked in this branch as well (though I can't promise that this branch is still up to date since some changes have been happening in develop, TF1/feature-optical, and vacuum_test in the last few months).
It would be worthwhile to rebase this branch against develop, …
> Formally merging sbujlab dose_track into JeffersonLab as cameron_dose_branch

- include/remolltypes.hh
- macros/runexample_envelope.mac
- src/remollEvent.cc
- variables.txt
Trajectory storage was looking for trackID < 2 (was intended to be <= 2, for moller generator purposes) and was then storing all trajectoryContainer[i]->getPoint().x/y/z information into a part branch leaf. We have changed it to check whether the trajectoryContainer[i]'s initial momentum magnitude is == part.p variable (within 0.001 MeV) and then assign a new part.trid variable to this. There is no change in functionality, but now one can define some hypothetical generator with an arbitrary number of mother particles, all of which will get their own unique trajectories successfully stored.
Potential RAM or hard disk storage changes:
- New part.trid variable
- Properly segment part.tj[xyz] information into the correct part branch positions so no data is duplicated
- A few new conditional …
> Fixing trajectory storage to work for all possible generators' parent particles

- geometry/mollerMother_dump.gdml
- geometry/mollerMother_merged.gdml
- geometry/mollerMother_noShlds.gdml
- geometry/mollerMother_parametrized.gdml
- geometry/mollerMother_showerMaxOnly.gdml
- geometry/mollerMother_trackingOnly.gdml
Whenever the hall wall and ceiling were included it was not placed at the right position relative to the target center. Was 4000 (not sure why) and is now 6087.0 based off of a measurement of the center of the pivots in the SBU MOLLER CAD. 
It is also possible that the radius of the hall or the relative offset of the roof and its radius of curvature are wrong as well, but I had (about a year ago) used a measurement of the radius from the JLab hall A CAD that is included in the SBU MOLLER CAD (and is centered on the pivot as well) to measure the wall radius, so it is likely correct.
> Geometry fixed hall center

- geometry/mollerMother_5open.gdml
- include/remollGenBeam.hh
- macros/runexample.mac
- macros/runexample_optical.mac
- macros/vis.mac
- src/remollGenBeam.cc
Most notably the /remoll/evgen/beam/origin macro command simply didn't work since there is no support for G4ThreeVector data types in DeclareMethodWithUnit(). 
Work around is to set the origin information as a new G4ThreeVector and access that object with a new DeclarePropertyWithUnit() command. 
I also went ahead and made the direction and polarization values into G4ThreeVectors. 
I also added a rudimentary G4RandFlat::shoot(min, max) for x and for y raster functions to the beam generator, which should help in detector parameter scans done with the beam generator (and is nice to have in general).
It may be nice to add a z axis G4RandFlat::shoot feature, and it may be nice to add one for the direction or polarization quantities as well, and to do so should be straightforward copying the …
> Feature improve beam generator

- analysis/issues/issue172.C
- include/remollDetectorConstruction.hh
- include/remollGenericDetector.hh
- macros/issues/issue172.mac
- src/remollActionInitialization.cc
- src/remollDetectorConstruction.cc
- src/remollGenericDetector.cc
Since this is a quite major set of changes to how some of the hits
are being stored, I am putting this in a bugfix branch first so I
can test optical photon hit behavior and let @cameronc137 take a look.
In any case, here's hit behavior:
- by default only hits are stored that satisfy the following:
- charge particle, energy > 0.1 MeV
- anywhere along a primary track
- first hit in volume for secondary track
- all hits (even those not stored) are added to the detector sums
To modify this behavior you can use
```
/remoll/SD/type 4001 lowenergyneutral
/remoll/SD/type 4001 secondaries
```
along with similar GDML statements (also possible: `opticalphotons`
and `boundaryhits`).
As for kryptonite, this was all moved to remollDetectorConstruction
and stepping action was removed (since now not …
> Bugfix to issue #172. Now kryptonite works again.

- analysis/issues/issue172.C
- include/remollGenericDetectorSum.hh
- src/remollGenericDetectorSum.cc
This seems to work fine now on the #172 test case.
For an electron hitting lead, only a subset of hits are stored (those with > 0.1 MeV energy, for example) but all are included in the sums. The pids 1000822060 and 1000822080 are lead 206 and 208 nuclei (see http://pdg.lbl.gov/2017/reviews/rpp2017-rev-monte-carlo-numbering.pdf if you are curious).
```
Lead
hit: 2.79084 0.250722 0.126983 0.751546 0.689868 0.136596 0.169301 1.72661 0.695538 0.00539331 0.232751 0.0403262 0.136237 0.624287 0.344374 0.638755 0.684848 0.231549 0.831656 1.49825 0.16947 0.233465 0.031472 0.214394 0.572451 0.593841 0.919408 0.0527639 0.66293 0.281838 0.386466 0.69345 0.653826 0.206384 0.727071 0.923065 1.09825 3.8036 0.773688 1.65728 4.2843 1.58518 0.969855 1.89878 2.54394 3.02038 0.554339 MeV
hit sum = 42.1183 …
```
> Merge feature-sums-refactor branch into develop

- .travis.yml
- include/remollEventAction.hh
- include/remollPrimaryGeneratorAction.hh
- macros/tests/unit/test_gen_pion.mac
- remoll.cc
- src/remollIO.cc
- src/remollPrimaryGeneratorAction.cc
This should fix the issue that travis doesn't indicate some test macro failures, as reported in #199. Submitting in a separate branch to trigger a travis build and test case to inspect.
> Bugfix issue 199

- geometry/hybridDaughter_merged.gdml
- geometry/mollerMother_merged.gdml
- geometry/subTargetRegion.gdml
- geometry/upstreamDaughter_merged.gdml
- include/remollDetectorConstruction.hh
- include/remollGenericDetector.hh
- macros/tests/unit/test_det_enable.mac
- macros/vis.mac
- src/remollDetectorConstruction.cc
- vis/vis.mac
Once again :-) by default remoll only stores hits:
- at the geometry boundary upon entering the sensitive detector volume,
- when the particle causing the hit is charged,
- when the particle has a kinetic energy above 0.1 MeV,
- and for primary particle also throughout the volume.
If you want to store more, you set DetType to "lowenenergyneutral", "secondaries", "opticalphoton" etc. What if you want to store both low energy neutrals and secondaries (like for a full shower)? It would seem logical that you can specify two DetType tags in the logical volume. Unfortunately that didn't work since in that case it only used the last DetType and ignore the earlier ones.
In this branch I rewrote how the auxiliary tags are parsed for the sensitive detector volumes. It's probably also a good …
> Merge bugfix to save all hits into develop

- include/remollGenericDetectorSum.hh
After the sum.by_pid functionality was changed to internally use
branches, I forgot to store the pid (std::map.first) in the vectors
that are written to the ROOT tree. All values of pid were still at 0.
> Save pid in sum.by_pid.pid ROOT branch.

- src/remollGenBeam.cc
Update default beam gen raster origin to -6.7 m, corr to 149 urad/mm, refz to 0.0 m
Fix to issue #242.
Raster is now by default 5 mm x 5 mm full size at the center of the
target (z = 0.0 mm) with an angle/position correlation of 149 urad/mm
corresponding with origin at -6.7 m per Jay's new designs.
> Update default beam gen raster origin

- CMakeLists.txt
This addresses issue #221 by adding the following
```
cmake -DADDITIONAL_FIELDS=ON ..
```
which will download upstreamSymmetric_sensR_0.0.txt and
hybridSymmetric_sensR_0.0.txt into map_directory.
Tried to solve this by introducing a separate make target but this was
faster and ultimately equivalent in documentation requirements.
> Add cmake option ADDITIONAL_FIELDS to download more fields

- include/remollGlobalField.hh
- macros/tests/unit/test_fields.mac
- src/remollGlobalField.cc
- src/remollMagneticField.cc
This follows up on PR #217 which was already merged, but where discussion indicated that gaps in fields can occur. Additional warnings will be added into develop through this PR, and field maps with upper boundaries of +180 deg are now allowed.
> Merge improvements to bfield header reading

- include/remollGlobalField.hh
- src/remollGlobalField.cc
- src/remollMagneticField.cc
Make remollMagneticFields static in remollGlobalField
This ensures that only a single set of fields takes up memory. Also made sure that the fields are only read in once. Added mutexes to avoid threading errors in issue #232 (which should now be resolved). Tested by running successfully with 64 threads (on my laptop, not very repeatable).
> Bugfix issue 232 threadsafe magnetic field

- include/remollGenTF1.hh
- src/remollGenTF1.cc
Avoid passing *new G4String since *new G4String introduced memory leaks since the pointer won't ever be cleaned up. If the main reason is passing by reference, then this does not present a sufficient performance gain since these are functions only called during initialization, not during running.
In general it would make sense for remollGenTF1 not to produce output on construction unless errors are encountered or a verbose flag is set. There may be a few more changes to this branch but I'm giving @cameronc137 a heads-up :)
> Enhancement to remollGenTF1 string operations

- geometry/pion/GEM/pionDetectorGEM.gdml
- include/remollIO.hh
- src/remollIO.cc
This branch ensures that the external xml entity files are stored in the ROOT file as well, and recreated when RecreateGDML is called on the ROOT file.
This works on things like:
```
<!DOCTYPE gdml [
<!ENTITY materials SYSTEM "pionMaterials.xml">
<!ENTITY matrices SYSTEM "../matrices.xml">
<!ENTITY matrices SYSTEM "/absolute/path/../../relative/path/matrices.xml">
]>
```
It will strip out the current working dir.
Fixes #254, so will close that one.
> Bugfix issue 254 save xml files

- include/remollglobs.hh
If you don't specify a beam current, it will determine rates based on 70 uA assumption.
You can still override with `/remoll/beamcurr 85 uA` etc. No changes beyond a single character...
> Changed default beam current to 65 uA (was 75 uA)

- .gitignore
- cmake/modules/BuildType.cmake
The default build type was Debug, which is about ~30% slower than
RelWithDebInfo, and RelWithDebInfo contains the same backtrace info.
This will make code faster (since typically run without changing the
default build type).
A specific build type can be chosen without the neeed to specify a
command line flag by creating a file .buildtype (which is ignored by
git) with as content e.g. Debug. This will persist between deletes
of the build directory (but changing the file will not cause a new
build type to take effect, this is only read on the first call to
cmake in an empty directory). The content of the file can still be
overridden with a command line argument: e.g.
```
cmake -DCMAKE_BUILD_TYPE=Release ..
```
> Bugfix: Set default build type to RelWithDebInfo

- src/remollGenericDetector.cc
Instead of selecting low energy neutrals on total energy, use kinetic energy
Effects:
- You may lose low energy neutral hits from massive neutral particles which
were stored in the output ROOT file until now: use `lowenergyneutrals` tag
to indicate that you want to store those hits after all.
- Anyone who already relied on the `lowenergyneutrals` tag will likely not
see a difference.
> Use kinetic energy in lowenergyneutrals

- .travis.yml
- Dockerfile
- scripts/tests/targz_macros.sh
Improvements for docker container, should reduce number of failed travis jobs due to concurrency issues. No effects on regular users (unless you rely on docker default run command, e.g. docker run jeffersonlab/remoll, which now will return -h output).
> Bugfix docker command passing

- src/remollGen12CElastic.cc
- src/remollGenMoller.cc
- src/remollGenpElastic.cc
- src/remollGenpInelastic.cc
Fixes issue #188 (also for other generators). Previously always used 2pi. Now using (fPh_max - fPh_min).
> Calculate phase factor on xs based on phi range thrown

- geometry/mollerMother_5open.gdml
- geometry/mollerMother_black.gdml
- geometry/positions.xml
- geometry/target/subTargetRegion.gdml
- geometry/target/target12C.gdml
- geometry/target/targetDaughter.gdml
- geometry/target/targetDaughter_Clamshell_Optimized.gdml
- geometry/target/targetDaughter_acceptanceDefinition.gdml
- geometry/target/targetDaughter_merged.gdml
- geometry/target/targetDaughter_noShlds.gdml
- geometry/upstream/upstreamDaughter_merged.gdml
- macros/gui.mac
- src/remollGenBeam.cc
This merges in the updated geometry in https://github.com/JeffersonLab/remoll/projects/12.
1. target goes 1.5 m downstream and is shortened to 1.25 m
2. upstream and hybrid both moved 1 m downstream
3. detectors move 0.5 m upstream
Distance between center of target and detector plane is 26.5 m.
Raster size referenced to center of target. Effective raster magnet position downstream by 1m
There is a remaining (large) volume overlap in mollerMother_merged.gdml. See below:
The rest seems ok.
> Enhancement updated geometry

- include/remollGlobalField.hh
- macros/runexample.mac
- src/remollGlobalField.cc
- src/remollMagneticField.cc
Instead of changing the fieldmaps, filenames, md5 checksum etc, we're just going to shift the field in the macro for now. This introduces that functionality.
> Bugfix: Messenger for field z offsets

- src/remollBeamTarget.cc
Due to a sign error, the events were generated around +4587 mm instead
of around -4587 mm. The call to GetFrameTranslation should have been a
call to GetTranslation, or various equivalent sign changes.
This was not a problem before since the target was centered at zero, and
so -0 is the same...
> Bugfix: Fix event generator to be in the target, not downstream (MAJOR)

- Dockerfile
The docker container now inherits from jlabce:2.3-mt at https://hub.docker.com/r/jeffersonlab/jlabce/tags for running on HPC clusters.
> Feature: Use JLabCE environment 2.3 with multi-threading in docker container

- include/remollSteppingAction.hh
- src/remollActionInitialization.cc
- src/remollSteppingAction.cc
Was #275 but now as PR against develop instead of master.
Removed the content of stepping initialization (was not use, was old) ￼…
This just referred to the old way of doing kryptonite and wasn't compiled in anyway. Better to have the files reflect what is actually compiled and included in the running.
> Bugfix: remove content of user stepping action

- .gitignore
- include/remollEventAction.hh
- include/remollIO.hh
- include/remollLinkDef.hh
- src/remollEventAction.cc
- src/remollIO.cc
Sometimes you want to inspect (or be able to repeat) specific events that you find in a ROOT file. This branch enables (optional) saving of the full random engine state for each event.
By telling geant4 to store the random state for each event with `/run/storeRndmStatToEvent 1` it will automatically be stored to the tree as the variable `seed`. With reroot or (ld pre-)loading libremoll.so you can then use things like:
```
T->Draw("seed.Save()","ev.A>-10")
```
which will save the random state for every event that has an asymmetry with magnitude less than 10 ppb to a file run[runno]evt[evtno].rndm. Arbitrary selection possible.
The files can be turned into input for /random/resetEngineFrom <filename>. See below for comments on file format.
The seed determines the random state uniquely but …
> Feature: Save full random state to ROOT file

- include/remollGenericDetectorHit.hh
- src/remollGenericDetector.cc
- src/remollGenericDetectorHit.cc
I think this commit adds output that will allow one to calculate the angle between the momentum and the volume where the hit occurs. The momentum vector is not translated but only rotated.
> Add local momentum to output

- include/remollDetectorConstruction.hh
- src/remollDetectorConstruction.cc
This sets the logical volume to kryptonite by name.
This avoids the need to do all the kryptonite by material type.
> Feature: /remoll/kryptonite/volume <logical_volume_name>

- include/remollGenericDetector.hh
- macros/tests/unit/test_det_enable.mac
- src/remollGenericDetector.cc
`/remoll/SD/detect_range <type> <range_begin> <range_end>`
This sets the detector type for all detectors within a range.
Example in test macro macros/tests/unit/test_det_enable.mac
> Feature: Ranged detector type cmd

- geometry/target/subTargetRegion.gdml
- geometry/target/targetDaughter_Clamshell_Optimized.gdml
- geometry/target/targetDaughter_acceptanceDefinition.gdml
The auxiliary tag TargetSamplingVolume indicates that that volume
can be *selected* as a primary vertex sampling volume, not that it
will be used as a sampling volume. You still have to select the
actual volume used with e.g. `/remoll/targname USAlTarg`. If you
pick a logical volume that does not have the TargetSamplingVolume
auxiliary tag in `targname` that will fail. Somehow the tag had
gotten removed in some target geometry, preventing them from being
used with the aluminum generator without gdml edits.
Here are the only steps that should be necessary for an aluminum
simulation (see `macros/tests/commit/test_elasticAl_DS.mac`):
```
/remoll/evgen/set elasticAl
/remoll/targname DSAlTarg
```
though you may want to tighten the generated angles for efficiency
as well.
> Bugfix: Activate the aux tag TargetSamplingVolume for Al US and DS windows

- src/remollGenAl.cc
When we moved to a single G_F definition (in units GeV^-2) instead
of a magical number without units, I forgot to remove the GeV^-2
from the asymmetry formula.
Double checked that this is not affecting any other places where
G_F is used.
@cipriangal Please test to see if this fixes the issue discussed
in the comments of 0c3fe73beefd38d04239a09ac33f5d911427173c
> Bugfix: Remove the explicit GeV^-2 units in A_PV(Al) generator

- remoll.cc
This becomes important for geant4.10.06 which fails to compile without this fix.
> Bugfix: Include G4Types first so G4MULTITHREADED before include G4RunManager

- src/remollTextFile.cc
This is necessary because deep down in the internal of ROOT TFile
writing there is a streamer call that uses strlen...
Maybe this is a fix for some of the random segfaults.
> Bugfix: Make the text file buffer one char larger and always end with '\0'.

- CMakeLists.txt
When geant4 is compiled with HDF5 support, the cmake test fails to
compile if the remoll project only includes CXX language. With also
C language included, the test succeeds.
This includes commits in #306, so that PR must be merged before this PR.
> Bugfix: CMake project requires C support when geant4 has HDF5 support

- geometry/target/subTargetRegion.gdml
- geometry/target/targetDaughter.gdml
- geometry/target/targetDaughter_Clamshell_Optimized.gdml
- geometry/target/targetDaughter_acceptanceDefinition.gdml
- geometry/target/targetDaughter_merged.gdml
- geometry/target/targetDaughter_noShlds.gdml
- src/remollBeamTarget.cc
- src/remollGenpElastic.cc
Addresses #322, it was the custom definition of LiquidHydrogen that failed the FIXME. With this fix, only properly formed materials are used in the target (for hydrogen and aluminum, still using an explicit 12C isotope).
Additional benefit, this now defines the proper ionisation energy of hydrogen in the target.
> Bugfix: use G4_lH2 instead of LiquidHydrogen

- src/remollDetectorConstruction.cc
This will print lines like
```
remoll: DetNo 8009 for pionDetectorLuciteReflectorInsideExitDetector_logical
remoll: already used by pionDetectorLeadDonut_logical
```
In many cases it may be intentional to have duplicate detector numbers,
for example when logical volumes are positioned not using replicated volumes.
This might then look like
```
remoll: DetNo 8002 for pionDetectorGEMSinglePlane_logical
remoll: already used by pionDetectorGEMSinglePlane_logical
```
> Flag duplicate detector number (but accept and proceed)

- CMakeLists.txt
- Dockerfile
- src/remollBeamTarget.cc
- src/remollGenTF1.cc
When looking through travis build logs for errors there are about 1300 lines of build logs which should fit in 200 or so. This makes it more difficult to find the actual continuous integration output from unit test macros, and therefore more likely that errors are overlooked.
> Bugfix: Reduce build output

- include/remollIO.hh
- src/remollIO.cc
This avoids some issues reading the ROOT file with uproot.
> Bugfix: Keep track of LV and SD names in map to avoid duplicates

- include/remollGenericDetector.hh
- include/remollGlobalField.hh
- remoll.cc
- src/remollDetectorConstruction.cc
- src/remollGenExternal.cc
- src/remollGlobalField.cc
- src/remollParallelConstruction.cc
- src/remollPhysicsList.cc
Remove 'unhelpful' output during running will make the unusual output stand out more. This removes some output that has low information content and moves other output behind level one verbose flags.
> Bugfix: Reduce run output

- macros/checkoverlap.mac
Fixes issue #288 related to having messenger commands with boolean arguments, which have to be entered, confusingly, as integers.
Now `/remoll/geometry/printoverlaps` basically calls `/remoll/geometry/printgeometry true` without the need for parsing.
> Fix #288 checkoverlap.mac to use `/remoll/geometry/printoverlaps`

- CMakeLists.txt
This just makes sure that the cmake install command uses the same version as the download command.
> Bugfix: Make sure the low-r fields v0.1 are installed as well

- src/remollDetectorConstruction.cc
- src/remollEvent.cc
- src/remollEventAction.cc
- src/remollParallelConstruction.cc
For some we could have used ranged-for but that is not possible for the majority which are daughter volume lookups.
> Bugfix: Remove all signed-unsigned warnings by using decltype

- geometry/upstream/upstreamDaughter_merged.gdml
Motivation: How you code the geometry matters in geant4. I've never seen a case where the main drag on the simulation (single highest nail) is the navigator in the geometry tree, yet here we are...
As tracks are stepped through the geometry, which is structured like a tree of nested volumes, the following operations are evaluated at every new step endpoint:
- Is the new endpoint still inside the current volume, and is it inside any daughter volumes of the current volume? G4VSolid::Inside(p)
- What is the distance of the new endpoint to the outside of the current volume along the current track direction? G4VSolid::DistanceToOut(p,dp)
- What is the distance of the new endpoint to the inside of any daughter volumes of the current volume along the current track direction? …
> Enhancement: geometry in upstream should avoid subtraction

- include/remollDetectorConstruction.hh
- macros/tests/unit/test_move_volume.mac
- src/remollDetectorConstruction.cc
Based on the name of an already placed physical volume you can now shift and rotate that volume. Takes the effort out of editing gdml (but can introduce overlaps).
Example:
```
/remoll/geometry/absolute_position h2Targ_PV (0,0,-5)
/run/beamOn 10
/remoll/geometry/relative_position h2Targ_PV (0,0,+5)
/run/beamOn 10
/remoll/geometry/absolute_rotation h2Targ_PV (0,90,0)
/run/beamOn 10
/remoll/geometry/relative_rotation h2Targ_PV (0,30,0)
/run/beamOn 10
```
(which makes no sense, but demonstrates the point).
The OpenGL visualization needs an interaction with the display for the change to be visible.
Unnamed physical volumes (`<physvol>...`) have name of the logical volume with `_PV` at the end.
> Feature: Macro commands to move volumes

- CMakeLists.txt
- macros/load_magnetic_fieldmaps.mac
- macros/runbatch_eAlelastic_down.mac
- macros/runbatch_eAlelastic_up.mac
- macros/runbatch_eAlinelastic_down.mac
- macros/runbatch_eAlinelastic_up.mac
- macros/runbatch_eAlquasielastic_down.mac
- macros/runbatch_eAlquasielastic_up.mac
- macros/runexample.mac
- macros/runexample_C12.mac
- macros/tests/commit/test_beam.mac
- macros/tests/commit/test_elastic.mac
- macros/tests/commit/test_elasticAl.mac
- macros/tests/commit/test_elasticAl_DS.mac
- macros/tests/commit/test_elasticAl_US.mac
- macros/tests/commit/test_inelastic.mac
- macros/tests/commit/test_inelasticAl.mac
- macros/tests/commit/test_moller.mac
- macros/tests/commit/test_pion.mac
- macros/tests/commit/test_power.mac
- macros/tests/commit/test_raster.mac
- macros/tests/release/test_moller.mac
- macros/tests/unit/test_fields.mac
- macros/tests/unit/test_polarization.mac
- macros/tests/valgrind/test_moller.mac
This also changes somewhat the method of loading magnetic field maps,
for easier maintenance. The current 'official' magnetic field maps are
loaded by the macros/load_magnetic_fieldmaps.mac macro. You are
encouraged to use `/control/execute macros/load_magnetic_fieldmaps.mac`
in your macros so you always have the latest field maps.
Current 'official' field maps:
```
/remoll/addfield map_directory/segmentedJLAB_v2.txt
/remoll/addfield map_directory/upstreamJLAB_v2.txt
```
(per discussion with @rahmans1) 
Since these are new fieldmaps, they will be downloaded for you when you run the next make or cmake.
> Feature: added hybridJLAB_v2, segmentedJLAB_v2, upstreamJLAB_v2
