JeffersonLab/remoll

- src/remollGlobalField.cc
Refs for in depth reading:
JLab CCPR https://misportal.jlab.org/mis/apps/ccpr/ccpr_user/ccpr_user_request_history.cfm?ccpr_number=153383
Upstream https://github.com/singularityware/singularity/issues/228
More upstream https://bugzilla.redhat.com/show_bug.cgi?id=1383739.
See also #50
> Fix for TMD5-caused crash on ifarm

- include/remollRun.hh
- include/remollRunData.hh
- macros/tests/test_seed.mac
- remoll.cc
- src/remollMessenger.cc
- src/remollRun.cc
> Hotfix random seed

- .github/ISSUE_TEMPLATE
- macros/checkoverlap.mac
- macros/pionwall/moller_lead_wall_100mm.in
- macros/pionwall/pion_lead_wall_100mm.in
- macros/printgeometry.mac
- macros/sim_dump_backscatter.mac
- macros/sim_moller.mac
- macros/sim_pion.mac
- macros/tests/commit/test_beam.mac
- macros/tests/commit/test_elastic.mac
- macros/tests/commit/test_elasticAl.mac
- macros/tests/commit/test_elasticAl_DS.mac
- macros/tests/commit/test_elasticAl_US.mac
- macros/tests/commit/test_inelastic.mac
- macros/tests/commit/test_inelasticAl.mac
- macros/tests/commit/test_moller.mac
- macros/tests/commit/test_pion.mac
- macros/tests/commit/test_raster.mac
- macros/tests/release/test_moller.mac
- macros/tests/unit/test_overlap.mac
- macros/tests/valgrind/test_moller.mac
> Bugfix dont use geometry sculpt

- analysis/issues/issue167.C
Just a single macro, really...
> Merge bugfix-issue167 into develop

- Dockerfile
Small fix, large increase in functionality.
> Put remoll in /jlab, run entrypoint exec with $*

- .travis.yml
- analysis/raster/plot_gen_beam_raster.C
- include/remollEventAction.hh
- include/remollGenBeam.hh
- include/remollPrimaryGeneratorAction.hh
- macros/tests/unit/test_gen_beam_raster.mac
- macros/tests/unit/test_gen_pion.mac
- remoll.cc
- src/remollGenBeam.cc
- src/remollIO.cc
- src/remollPrimaryGeneratorAction.cc
See #190 for demonstration of this functionality. This will be merged into the beam generator class in develop before v2.1_rc later this week.
> Feature gen beam correlated raster

- analysis/raster/plot_gen_beam_raster.C
- include/remollGenBeam.hh
- macros/tests/unit/test_gen_beam_raster.mac
- src/remollGenBeam.cc
Updated test macro with reference position command
(/remoll/evgen/beam/rasrefz -5 m)
Updated test analysis script to create plots at US and DS target window
> Raster reference position command, set default to US target window

- src/remollMagneticField.cc
small change in how we process the header for the magnetic field. The configuration before did not allow the map to start at -180 degrees.
> update range to accept -180 deg. give more information on fail

- .travis.yml
- analysis/tests/test_general.C
- scripts/tests/targz_macros.sh
Not a solution for #226, won't be merged into develop.
> Save pdf files instead of png to get past #226

- macros/tests/commit/test_pion.mac
- src/remollGenPion.cc
This works around issue #231 (but doesn't solve it).
> Run pion test simulation with single thread

- CMakeLists.txt
- macros/manual.mac
- manual.txt
It adds two make targets that are not included in ALL, so they should be harmless.
No change to default behavior.
```
cd build
make 
make check-manual
```
This should currently display a diff to allow for testing the proper behavior. Ultimately it will be replaced with an up-to-date manual.txt so no diff should be shown.
> Feature make check manual

- .travis.yml
- Dockerfile
- scripts/tests/watermark.sh
Example of output below
[rootfiles_tests_commit_analysis.pdf](https://github.com/JeffersonLab/remoll/files/2993829/rootfiles_tests_commit_analysis.pdf)
Obtained with
```
scripts/tests/test_macros.sh commit
scripts/tests/watermark.sh rootfiles/tests/commit/analysis
```
and what would be uploaded as a release product.
> Feature: Create pdf booklet of standardized plots

- include/remollMagneticField.hh
- src/remollGlobalField.cc
- src/remollMagneticField.cc
This pull requests modifies the magnetic field interpolation routines to avoid a number of expensive function calls that are required at every step. Not sure there's as much impact as profiling promised there would be...
> Bugfix issue 252 slow magnetic field lookups

- include/remollGenericDetector.hh
- include/remollGenericDetectorSum.hh
- include/remolltypes.hh
- src/remollGenericDetector.cc
- src/remollGenericDetectorSum.cc
E.g. `/remoll/SD/summary 28` to print running sum for main detector virtual plane (no energy deposit expected here).
> /remoll/SD/summary <detno> to print summary at end of run

- src/remollIO.cc
> Bugfix: Initialize remollIO::fRate to zero

- analysis/basicAna.C
- geometry/hybrid/hybridDaughter_merged.gdml
- geometry/mollerMother_merged.gdml
- geometry/upstream/upstreamBeampipe.gdml
> Test hevac addbeampipe

- geometry/hybrid/hybridDaughter_merged.gdml
Merging latest collar definitions from Chandan
> Updated lead collars and beampipe design

- analysis/basicAna.C
- analysis/usShieldingAna.C
- geometry/hybrid/hybridDaughter_merged.gdml
- geometry/target/subTargetRegion.gdml
- geometry/upstream/upstreamDaughter_merged.gdml
- macros/runBeam.mac
- macros/runEE.mac
- macros/runEPpion.mac
Need to resolve conflicts before merge.
> Test hevac add tgt coll1 shlding

- geometry/hybrid/hybridDaughter_merged.gdml
bringing in changes to beampipe from Chandan's branch
> modified beampipe dimension

- analysis/anaConst.h
- analysis/det28Histos.h
- analysis/radAna.C
- geometry/hall/hallDaughter_dump.gdml
- geometry/mollerMother_merged.gdml
- geometry/mollerParallel.gdml
- geometry/positions.xml
Bringing test-hevac-lintelsandcollars up-to-date with target shielding branch
> Bringing test-hevac-lintelsandcollars up-to-date with target shielding branch

- geometry/target/subTargetRegion.gdml
See discussion at
https://github.com/JeffersonLab/remoll/commit/7b76ce8acadb709e2195fed60968e7279ece6952
> Bugfix: Move target outer detectors to be inline with experiment axis

- geometry/upstream/upstreamDaughter_merged.gdml
This pull request fixes some geometry bug in the previous commit.
> fixed some geometry issue with the prevoius merge

- geometry/beampipe/premoller/beampipeRaster.gdml
- geometry/mollerMother_merged.gdml
- geometry/target/subTargetRegion.gdml
> Feature: Add pre-moller vacuum beampipe outside the target region

- geometry/hybrid/hybridDaughter_merged.gdml
- geometry/hybrid/hybridToroid.gdml
- geometry/upstream/upstreamToroid.gdml
merging the epoxy coils into the magnet hotspot branch
> Feature coilwithepoxy
